tarefa_processamento_completo:
  description: >
    Processar o arquivo financeiro localizado em {file_path}.
    O processo completo é:
    
    1.  **USAR A FERRAMENTA:** Primeiro, use a `PDFTableExtractorTool` 
        com o `file_path` para extrair todos os dados tabulares do PDF.
    
    2.  **ANALISAR E FORMATAR:** Analise os dados retirados das tabelas
        e execute as seguintes ações:
    
    3.  **Filtrar:** Ignore mentalmente todas as linhas que são 
        cabeçalhos ("Data", "Movimentação"), rodapés ("Total"), saldos 
        ("Saldo do dia:") ou qualquer texto que não seja uma transação real.
    
    4.  **Extrair:** Para cada transação real que encontrar, extraia:
        - 'data': A data da transação. (Atenção: em extratos, a data 
          pode ser um cabeçalho de seção).
        - 'nome': A descrição da transação.
        - 'valor': O valor (sempre positivo, remova "R$" ou "-").
        - 'entrada ou saída': Determine se é 'entrada' ou 'saída'.
    
    5.  **Categorizar:** Classifique a transação em uma das categorias: 
        [Alimentação, Moradia, Transporte, Saúde, Educação, Lazer, 
        Dívidas e Empréstimos, Despesas Pessoais, Impostos e Taxas, 
        Receitas (Salário/Renda), Investimentos, Resgates, 
        Serviços Financeiros, Depósitos e Saques, Outros].

    Compile TODAS as transações válidas que você encontrar em um único 
    objeto JSON formatado.
    
    **IMPORTANTE: Não invente dados. Se os dados da ferramenta 
    estiverem vazios ou não contiverem transações, retorne um JSON 
    com uma lista vazia.**
    
  agent: agente_processador_financeiro
  expected_output: >
    Um único bloco de string JSON contendo uma lista de todas as transações, 
    cada uma com 'data', 'nome', 'valor', 'categoria' e 'entrada ou saída'.