tarefa_processamento_completo:
  description: >
    Processar o arquivo financeiro localizado em {file_path}.
    O processo completo é:
    
    1.  **PRIMEIRA TENTATIVA:** Use a ferramenta "Extrator de PDF Nativo". 
        Esta é a ferramenta preferida e mais rápida.
    
    2.  **CRITÉRIO PARA OCR:** Use a ferramenta "Extrator de PDF (OCR)" 
        APENAS se a "Extrator de PDF Nativo" retornar um erro explícito 
        (especialmente "O PDF parece ser uma imagem") OU se retornar 
        menos de 50 caracteres de texto útil. 
        Se o extrator nativo retornar texto substancial (mais de 50 caracteres),
        NÃO use o OCR - prossiga diretamente para a análise.
    
    3.  **ANALISAR E FORMATAR:** Assim que tiver o texto de UMA das ferramentas,
        analise-o COMPLETAMENTE e MINUCIOSAMENTE.

    4.  **VARREDURA COMPLETA:** Examine CADA linha do texto extraído.
        Procure por TODOS os padrões de transação, incluindo:
        - Linhas com valores monetários (R$ X,XX)
        - Linhas com datas seguidas de descrições e valores
        - Linhas que contenham nomes de estabelecimentos
        - Linhas isoladas de valores que possam estar relacionadas à linha anterior
        - Linhas com códigos de transação ou referências
        
    5.  **Filtrar:** Ignore APENAS:
        - Cabeçalhos explícitos ("Data", "Movimentação", "Histórico")
        - Rodapés de totais ("Total da fatura", "Total de compras")
        - Informações de saldo quando não forem transações
        - Informações de taxas e juros quando forem apenas informativos
        
    6.  **EXTRAIR TODAS:** Para CADA transação que encontrar, extraia:
        - 'data': A data da transação (formato YYYY-MM-DD se possível)
        - 'descricao': A descrição/nome da transação
        - 'valor': O valor (sempre positivo como float, remova "R$", "-", vírgulas)
        - 'tipo': Determine se é 'despesa' ou 'receita'
        - 'parcelado': Analise se a transação é parcelada (procure por indicadores como "1/12", "2/10", "PARC", "PARCELA", etc.)
        - 'numero_parcelas': Se parcelado, extraia o número atual da parcela
        - 'total_parcelas': Se parcelado, extraia o total de parcelas
    
    7.  **IMPORTANTE:** Se encontrar linhas com apenas valores (ex: "R$ 228,66") 
        que estejam próximas a descrições em linhas separadas, 
        tente relacioná-las à transação mais provável.
        
    8.  **Categorizar e Subcategorizar:** Para cada transação, classifique primeiro em uma categoria principal e depois em uma subcategoria específica:
        
        **CATEGORIAS PRINCIPAIS:**
        - MORADIA
        - COMUNICACAO  
        - ALIMENTACAO
        - TRANSPORTE
        - SAUDE
        - CUIDADO_PESSOAL
        - EDUCACAO
        - LAZER
        - SERVICOS_FINANCEIROS
        - DIVERSOS
        
        **SUBCATEGORIAS por categoria (com exemplos de palavras-chave):**
        
        MORADIA: 
        • Condomínio (ex: condomínio, taxa condominial)
        • Aluguel (ex: aluguel, locação)
        • Energia Elétrica (ex: Enel, Light, Cemig, energia, elétrica)
        • Gás (ex: Ultragaz, Liquigás, gás)
        • Água (ex: Sabesp, Cedae, água, saneamento)
        • Serviços de limpeza / Faxina (ex: faxina, limpeza, diarista)
        • Reforma / Manutenção / Jardineiro (ex: reforma, pintura, jardineiro, manutenção)
        • Outras
        
        COMUNICACAO: 
        • Telefone Celular (ex: Vivo, Tim, Claro, Oi, celular, telefone)
        • Combo (TV + Internet + Tel) (ex: Sky, Net, Vivo Fibra, internet, TV)
        • Apps (Netflix, Spotify, Prime, etc) (ex: Netflix, Spotify, Amazon Prime, Disney+, YouTube Premium, Apple Music, Deezer, HBO Max, Paramount+, apps, streaming)
        • Outros
        
        ALIMENTACAO: 
        • Supermercado (ex: Pão de Açúcar, Carrefour, Extra, supermercado, mercado)
        • Refeições em restaurante (ex: restaurante, lanchonete, fast food, McDonald's, Burger King, iFood, Uber Eats, delivery)
        • Feira (ex: feira, hortifruiti, sacolão)
        • Padaria (ex: padaria, pão, confeitaria)
        • Outros
        
        TRANSPORTE: 
        • Combustível (ex: Petrobras, Shell, Ipiranga, posto, gasolina, etanol, combustível)
        • Seguro (ex: seguro auto, Porto Seguro, Bradesco Seguros)
        • IPVA (ex: IPVA, imposto veículo)
        • Licenciamento (ex: licenciamento, DETRAN)
        • Manutenção (ex: oficina, mecânico, troca óleo, revisão, pneu)
        • Estacionamento (ex: estacionamento, zona azul, parking)
        • Pedágio (ex: pedágio, CCR, Ecovias)
        • Multas (ex: multa, infração, DETRAN)
        • Uber (ex: Uber, 99, taxi, transporte app, Cabify)
        • Lavagem / Higienização (ex: lava jato, lavagem, enceramento)
        • Outros
        
        SAUDE: 
        • Plano de Saúde (ex: Unimed, Bradesco Saúde, SulAmérica, plano saúde)
        • Dentista (ex: dentista, ortodontia, odontologia)
        • Medicamentos / Farmácia (ex: Drogaria, Farmácia, medicamento, remédio, Drogasil, Pacheco)
        • Terapia / Tratamentos Contínuos (ex: fisioterapia, psicologia, terapia)
        • Exames fora do plano (ex: laboratório, exame, Fleury, Dasa)
        • Outras Consultas Fora do Plano (ex: consulta particular, médico particular)
        • Outros
        
        CUIDADO_PESSOAL: 
        • Vestuário / Calçados / Acessórios (ex: roupa, sapato, tênis, Zara, C&A, Renner, Shopping)
        • Higiene pessoal (ex: shampoo, sabonete, perfume, O Boticário, Natura)
        • Lavanderia (ex: lavanderia, tinturaria, lavagem roupa)
        • Salão / Barbeiro / Manicure (ex: salão, cabeleireiro, barbeiro, manicure, estética)
        • Academia / Esportes (ex: academia, Smart Fit, ginástica, pilates, crossfit)
        • Suplemento Alimentar (ex: whey, suplemento, Growth, Integral Médica)
        • Outros
        
        EDUCACAO: 
        • Graduação (ex: faculdade, universidade, graduação, mensalidade)
        • Pós-Graduação (ex: pós, MBA, mestrado, doutorado, especialização)
        • Cursos e Congressos (ex: curso, congresso, seminário, workshop)
        • Cursos de Extensão (ex: extensão, certificação, capacitação)
        • Mentorias (ex: mentoria, coaching, consultoria educacional)
        • Idiomas (ex: inglês, espanhol, Wizard, CNA, CCAA, idioma)
        • Outros
        
        LAZER: 
        • Cinema / Teatro / Shows/ Jantares (ex: cinema, teatro, show, concerto, jantar, bar, balada, festa, entretenimento)
        • Livros (ex: livro, livraria, Saraiva, Amazon livros, literatura)
        • Viagens (ex: viagem, hotel, pousada, passagem, avião, ônibus, rodoviária, aeroporto, Booking, Airbnb, Latam, Gol, Azul, Delta, American Airlines, United, TAP, companhia aérea)
        • Outros
        
        SERVICOS_FINANCEIROS: 
        • Tarifas Bancárias (ex: tarifa, banco, taxa bancária, manutenção conta)
        • Anuidade Cartão Crédito (ex: anuidade, cartão crédito, Visa, Mastercard)
        • Transferências (ex: transferência, PIX, TED, DOC)
        • Depósitos (ex: depósito, aplicação)
        • Outros
        
        DIVERSOS: 
        • Animais de estimação (ex: pet shop, veterinário, ração, animal)
        • Presentes (ex: presente, gift, loja presente)
        • Doações (ex: doação, caridade, ONG)
        • Impostos (ex: imposto de renda, IRPF, tributo, receita federal)
        • Advogado (ex: advogado, advocacia, jurídico, cartório)
        • Outros
        
        **INSTRUÇÕES CRÍTICAS DE CATEGORIZAÇÃO:**
        - EVITE usar DIVERSOS como primeira opção - use apenas quando realmente não houver outra categoria aplicável
        - Analise MUITO cuidadosamente o nome da transação antes de categorizar
        - Procure por palavras-chave específicas mencionadas nos exemplos
        - Se encontrar uma palavra-chave específica (ex: "Spotify"), use a subcategoria correspondente (ex: COMUNICACAO > Apps)
        - Para companhias aéreas (Delta, Latam, Gol, etc.), sempre use LAZER > Viagens
        - Para serviços de streaming (Netflix, Spotify, etc.), sempre use COMUNICACAO > Apps
        - Para restaurantes, lanchonetes, delivery, sempre use ALIMENTACAO > Refeições em restaurante
        - Para postos de gasolina, sempre use TRANSPORTE > Combustível
        - Para farmácias e drogarias, sempre use SAUDE > Medicamentos / Farmácia
        - Se não encontrar uma correspondência exata, use a categoria mais lógica baseada no contexto
        - APENAS use DIVERSOS quando a transação realmente não se encaixar em nenhuma das outras 9 categorias
        
        **DETECÇÃO DE PARCELAMENTO:**
        - Procure por padrões como: "1/12", "02/10", "PARC 3/6", "PARCELA 1 DE 12", "(3/9)"
        - Se encontrar, defina parcelado=true e extraia os números
        - Se não encontrar indicadores, defina parcelado=false, numero_parcelas=null, total_parcelas=null
        
        **REGRA CRÍTICA DE EXTRAÇÃO COMPLETA:**
        - NUNCA pule uma transação que tenha um valor monetário identificável
        - Se uma linha contém R$ seguido de um número, considere-a uma possível transação
        - Prefira incluir transações duvidosas a omiti-las
        - Se não conseguir identificar a descrição completa, use o texto disponível
        - Para linhas com valores isolados, tente associar com contexto próximo
        
        **TIPO DE DOCUMENTO:**
        - Se contém cabeçalhos como "FATURA", "CARTÃO", "CARD", use "credit-card-statement"
        - Se contém "EXTRATO", "CONTA CORRENTE", "POUPANÇA", use "extrato"  
        - Se não conseguir determinar, use "other"

    Compile TODAS as transações válidas que você encontrar em um único 
    objeto JSON formatado seguindo esta estrutura:
    
    {
      "success": true,
      "bank_name": "TBD",
      "document_type": "[DETERMINE: 'extrato' para extratos bancários, 'credit-card-statement' para faturas de cartão, 'other' para outros tipos]",
      "transactions_count": [NÚMERO_TOTAL_DE_TRANSAÇÕES],
      "transactions": [
        {
          "uuid": "1",
          "data": "YYYY-MM-DD",
          "descricao": "Descrição da transação",
          "valor": 99.99,
          "categoria": "CATEGORIA_PRINCIPAL",
          "tipo": "despesa ou receita",
          "subcategoria": "Subcategoria específica",
          "parcelado": true
          // APENAS inclua os campos abaixo SE parcelado=true:
          "numero_parcelas": 1,
          "total_parcelas": 12
        },
        {
          "uuid": "1",
          "data": "YYYY-MM-DD",
          "descricao": "Outra transação não parcelada",
          "valor": 50.00,
          "categoria": "ALIMENTACAO",
          "tipo": "despesa",
          "subcategoria": "Supermercado",
          "parcelado": false
          // Não incluir numero_parcelas e total_parcelas quando parcelado=false
        }
      ],
      "error_message": null
    }
    
    **IMPORTANTE SOBRE UUID:** Sempre use "1" para TODAS as transações. Não numere sequencialmente (1, 2, 3...). O uuid representa o ID do usuário, não da transação.
    
    **IMPORTANTE SOBRE PARCELAMENTO:** Se parcelado=false, NÃO inclua os campos numero_parcelas e total_parcelas no JSON.
    
    **IMPORTANTE: Não invente dados. Se os dados da ferramenta 
    estiverem vazios ou não contiverem transações, retorne:**
    
    {
      "success": false,
      "bank_name": "TBD", 
      "document_type": "unknown",
      "transactions_count": 0,
      "transactions": [],
      "error_message": "Nenhuma transação encontrada no documento"
    }
    
  agent: agente_processador_financeiro
  expected_output: >
    Um objeto JSON completo seguindo a estrutura ExtractionResult com todos os campos necessários:
    success, bank_name, document_type, transactions_count, transactions (com todos os campos incluindo 
    uuid, data, descricao, valor, categoria, tipo, subcategoria, parcelado, numero_parcelas, total_parcelas) 
    e error_message.